language: python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - mkdocs build
before_deploy:
  # Decrypt the GitHub Deploy Key using instructions from `travis encrypt-file`
  - openssl aes-256-cbc -K $encrypted_b98ae82d81f1_key -iv $encrypted_b98ae82d81f1_iv -in travis-deploy-key.enc -out travis-deploy-key -d
  - chmod 600 travis-deploy-key
  # Start an ssh-agent in the background and load the Deploy Key
  - eval "$(ssh-agent -s)"
  - ssh-add travis-deploy-key
  # Record minimal build information in the Git user identity
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Switch the origin from HTTPS to SSH and setup the branch, so that we can use the Deploy Token
  - git remote set-url origin git@github.com:copperlight/copperlight.github.io.git
  - git remote set-branches --add origin master
  - git fetch origin master:master
deploy:
  provider: script
  script: mkdocs gh-deploy --remote-branch master
  skip_cleanup: true
  on:
    branch: source
    condition: $TRAVIS_PULL_REQUEST = false
