site_name: Copperlight Writes
site_url: 'http://copperlight.github.io/'
repo_url: 'https://github.com/copperlight/copperlight.github.io'
edit_uri: ''
site_description: A site for knowledge sharing and neat things.
site_author: Matthew Johnson
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
google_analytics: ['UA-52382416-1', 'copperlight.github.io']
remote_branch: master

strict: True

pages:
- Home: index.md
- Ansible:
  - Ansible Vault and SSH Key Distribution: ansible/ansible-vault-and-ssh-key-distribution.md
  - Running Ansible Playbooks on Windows: ansible/running-ansible-playbooks-on-windows.md
  - Testing Ansible Galaxy Roles with Docker: ansible/testing-ansible-galaxy-roles-with-docker.md
- AWS:
  - Assume Role with AWSCLI: aws/assume-role-with-awscli.md
  - AWS Credential Files for Java and Python: aws/aws-credential-files-for-java-and-python.md
  - Build a Fake Instance Metadata Server for Ubuntu on Vagrant: aws/build-a-fake-instance-metadata-server-for-ubuntu-on-vagrant.md
  - Checking and Changing Content-Type of S3 Object with AWSCLI: aws/checking-and-changing-content-type-of-s3-object-with-awscli.md
  - Configuring Multiple Interfaces on the Same Network in EC2: aws/configuring-multiple-interfaces-on-the-same-network-in-ec2.md
- GitHub:
  - How I Built My Site: github/how-i-built-my-site.md
- Linux:
  - Linux ftrace Delivers dtrace-like Functionality: linux/linux-ftrace-delivers-dtrace-like-functionality.md
- Misc:
  - Clone Stash Pull Requests: misc/clone-stash-pull-requests.md
  - Dual Boot OSX 10.10 and Ubuntu 14.04 on a 2013 Macbook Pro Retina: misc/dual-boot-osx-10.10-and-ubuntu-14.04-on-a-2013-macbook-pro-retina.md
  - Reset Jenkins Build Number: misc/reset-jenkins-build-number.md
  - Switching JDKs in OSX: misc/switching-jdks-in-osx.md
- Python:
  - Accessing Google APIs with Python: python/accessing-google-apis-with-python.md
  - Building REST APIs with Python Flask: python/building-rest-apis-with-python-flask.md
  - Install the Latest Python Versions on Mac OSX: python/install-the-latest-python-versions-on-macosx.md
  - Memory Profiling with Pyrasite and Heapy: python/memory-profiling-with-pyrasite-and-heapy.md
  - Stop Using "print" for Debugging: python/stop-using-print-for-debugging.md
- Scala:
  - IntelliJ Configuration Tips: scala/intellij-configuration-tips.md
  - Overview of Debugging Tools: scala/overview-of-debugging-tools.md
  - Scalafmt Configuration Tips: scala/scalafmt-configuration-tips.md
  - Starting Scala REPLs with Gradle and SBT: scala/starting-scala-repls-with-gradle-and-sbt.md
  - Testing AWS Clients with IAM AssumeRole Credentials in Scala: scala/testing-aws-clients-with-iam-assumerole-credentials-in-scala.md
  - Using Gradle to Run Scala Projects Locally: scala/using-gradle-to-run-scala-projects-locally.md
  - Using the Scala REPL to Configure Amazon SES Notifications: scala/using-the-scala-repl-to-configure-amazon-ses-notifications.md
- Shell:
  - Measuring Transfer Speed Over Time with cURL: shell/measuring-transfer-speed-over-time-with-curl.md
  - Parsing JSON on the Command Line: shell/parsing-json-on-the-command-line.md
  - pet - CLI Snippet Manager: shell/pet-cli-snippet-manager.md
  - Schedule Ad-Hoc Jobs for Later on an Instance with atd: shell/schedule-ad-hoc-jobs-for-later-on-an-instance-with-atd.md
- Talks:
  - A Better Scala REPL: talks/a-better-scala-repl.md
  - Amazon S3 and Elastic MapReduce to Monitor at Gigascale: talks/amazon-s3-elastic-mapreduce-to-monitor-at-gigascale.md
  - Are We There Yet?: talks/are-we-there-yet.md
  - Automating Your Browser and Desktop Apps: talks/automating-your-browser-and-desktop-apps.md
  - Beyond PEP 8 Best Practices for Beautiful Intelligible Code: talks/beyond-pep-8-best-practices-for-beautiful-intelligible-code.md
  - Boot Can Build It: talks/boot-can-build-it.md
  - Bottom Up vs Top Down Design in Clojure: talks/bottom-up-vs-top-down-design-in-clojure.md
  - Built-In Super Heroes: talks/built-in-super-heroes.md
  - Clojure Concurrency: talks/clojure-concurrency.md
  - Clojure core.async: talks/clojure-core-async.md
  - Clojure Made Simple: talks/clojure-made-simple.md
  - Clojure Parallelism Beyond Futures: talks/clojure-parallelism-beyond-futures.md
  - ClojureScript for Skeptics: talks/clojurescript-for-skeptics.md
  - Composing Interactive Apps with Zelkova: talks/composing-interactive-apps-with-zelkova.md
  - Dagobah - A Data-Centric Meta-Scheduler: talks/dagobah-a-data-centric-meta-scheduler.md
  - Debugging Clojure Code with Cursive: talks/debugging-clojure-code-with-cursive.md
  - Design and Prototype a Language in Clojure: talks/design-and-prototype-a-language-in-clojure.md
  - Developing ClojureScript with Figwheel: talks/developing-clojurescript-with-figwheel.md
  - Fear and Awaiting in Async: talks/fear-and-awaiting-in-async.md
  - From 0 to Prototype Using ClojureScript Re-Frame and Friends: talks/from-0-to-prototype-using-clojurescript-re-frame-and-friends.md
  - Hammock Driven Development: talks/hammock-driven-development.md
  - Handmade Hero Day 001 - Setting Up the Windows Build: talks/handmade-hero-day-001-setting-up-the-windows-build.md
  - Interactive Programming Flappy Bird in ClojureScript: talks/interactive-programming-flappy-bird-in-clojurescript.md
  - Logging and Testing and Debugging Oh My: talks/logging-and-testing-and-debugging-oh-my.md
  - Machete-Mode Debugging Hacking Your Way Out of a Tight Spot: talks/machete-mode-debugging-hacking-your-way-out-of-a-tight-spot.md
  - Monitoring Monitoring Systems at Netflix: talks/monitoring-monitoring-systems-at-netflix.md
  - Netflix Atlas Telemetry - A Platform Begets an Ecosystem: talks/netflix-atlas-telemetry-a-platform-begets-an-ecosystem.md
  - Parallel Programming Fork Join and Reducers: talks/parallel-programming-fork-join-and-reducers.md
  - Parsing Text with a Virtual Machine: talks/parsing-text-with-a-virtual-machine.md
  - Python as a Configuration Language: talks/python-as-a-configuration-language.md
  - Python Concurrency from the Ground Up: talks/python-concurrency-from-the-ground-up.md
  - Python Language - PyCon 2016: talks/python-language-pycon-2016.md
  - Python vs Ruby - A Battle to the Death: talks/python-vs-ruby-a-battle-to-the-death.md
  - REPL Based Development Demo: talks/repl-based-development-demo.md
  - Refactoring Python Why and How to Restructure Your Code: talks/refactoring-python-why-and-how-to-restructure-your-code.md
  - Removing Pythons GIL - The Gilectomy: talks/removing-pythons-gil-the-gilectomy.md
  - Rethinking the Developer Career Path: talks/rethinking-the-developer-career-path.md
  - Rich Hickey on clojure.spec: talks/rich-hickey-on-clojure-spec.md
  - Simple Made Easy: talks/simple-made-easy.md
  - Spec-ulation Keynote: talks/spec-ulation-keynote.md
  - Stop Writing Classes: talks/stop-writing-classes.md
  - The Joys and Perils of Interactive Development: talks/the-joys-and-perils-of-interactive-development.md
  - The Packaging Gradient: talks/the-packaging-gradient.md
  - The ReactJS Landscape: talks/the-reactjs-landscape.md
  - The Unix Chainsaw: talks/the-unix-chainsaw.md
  - Think Like a Pythonista: talks/think-like-a-pythonista.md
  - Thinking in Coroutines: talks/thinking-in-coroutines.md
  - To Mock or Not To Mock That is the Question: talks/to-mock-or-not-to-mock-that-is-the-question.md
  - Types are Like the Weather Type Systems are Like Weathermen: talks/types-are-like-the-weather-type-systems-are-like-weathermen.md
  - Wat - A Lightning Talk: talks/wat-a-lightning-talk.md
  - Writing Awesome Command Line Programs in Python: talks/writing-awesome-command-line-programs-in-python.md

theme: material

extra:
  font:
    code: 'Menlo'

extra_css:
- css/custom.css

extra_javascript:
- https://buttons.github.io/buttons.js

markdown_extensions:
- admonition
- codehilite
- pymdownx.tilde
- toc:
    permalink: True
