site_name: Copperlight Writes
site_url: 'http://copperlight.github.io/'
repo_url: 'https://github.com/copperlight/copperlight.github.io'
edit_uri: ''
site_description: A site for knowledge sharing and neat things.
site_author: Matthew Johnson
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
google_analytics: ['UA-52382416-1', 'copperlight.github.io']
remote_branch: master

strict: True

nav:
- Home: index.md
- Ansible:
  - Ansible Vault and SSH Key Distribution: ansible/ansible-vault-and-ssh-key-distribution.md
  - Running Ansible Playbooks on Windows: ansible/running-ansible-playbooks-on-windows.md
  - Testing Ansible Galaxy Roles with Docker: ansible/testing-ansible-galaxy-roles-with-docker.md
- AWS:
  - Assume Role with AWSCLI: aws/assume-role-with-awscli.md
  - AWS Credential Files for Java and Python: aws/aws-credential-files-for-java-and-python.md
  - Build a Fake Instance Metadata Server for Ubuntu on Vagrant: aws/build-a-fake-instance-metadata-server-for-ubuntu-on-vagrant.md
  - Checking and Changing Content-Type of S3 Object with AWSCLI: aws/checking-and-changing-content-type-of-s3-object-with-awscli.md
  - Configuring Multiple Interfaces on the Same Network in EC2: aws/configuring-multiple-interfaces-on-the-same-network-in-ec2.md
- GitHub:
  - How I Built My Site: github/how-i-built-my-site.md
- Linux:
  - Linux ftrace Delivers dtrace-like Functionality: linux/linux-ftrace-delivers-dtrace-like-functionality.md
- Misc:
  - Clone Stash Pull Requests: misc/clone-stash-pull-requests.md
  - Dual Boot OSX 10.10 and Ubuntu 14.04 on a 2013 Macbook Pro Retina: misc/dual-boot-osx-10.10-and-ubuntu-14.04-on-a-2013-macbook-pro-retina.md
  - Reset Jenkins Build Number: misc/reset-jenkins-build-number.md
  - Switching JDKs in OSX: misc/switching-jdks-in-osx.md
- Python:
  - Accessing Google APIs with Python: python/accessing-google-apis-with-python.md
  - Building REST APIs with Python Flask: python/building-rest-apis-with-python-flask.md
  - Install the Latest Python Versions on Mac OSX: python/install-the-latest-python-versions-on-macosx.md
  - Memory Profiling with Pyrasite and Heapy: python/memory-profiling-with-pyrasite-and-heapy.md
  - Stop Using "print" for Debugging: python/stop-using-print-for-debugging.md
- Recipes:
  - Galaxy's Best Margarita: recipes/galaxys-best-margarita.md
- Running:
  - Garmin 935 Navigation: running/garmin-935-navigation.md
- Scala:
  - IntelliJ Configuration Tips: scala/intellij-configuration-tips.md
  - JMH Testing with Scala: scala/jmh-testing-with-scala.md
  - Overview of Debugging Tools: scala/overview-of-debugging-tools.md
  - Scalafmt Configuration Tips: scala/scalafmt-configuration-tips.md
  - Starting Scala REPLs with Gradle and SBT: scala/starting-scala-repls-with-gradle-and-sbt.md
  - Testing AWS Clients with IAM AssumeRole Credentials in Scala: scala/testing-aws-clients-with-iam-assumerole-credentials-in-scala.md
  - Using Gradle to Run Scala Projects Locally: scala/using-gradle-to-run-scala-projects-locally.md
  - Using the Scala REPL to Configure Amazon SES Notifications: scala/using-the-scala-repl-to-configure-amazon-ses-notifications.md
- Shell:
  - Measuring Transfer Speed Over Time with cURL: shell/measuring-transfer-speed-over-time-with-curl.md
  - Parsing JSON on the Command Line: shell/parsing-json-on-the-command-line.md
  - pet - CLI Snippet Manager: shell/pet-cli-snippet-manager.md
  - Schedule Ad-Hoc Jobs for Later on an Instance with atd: shell/schedule-ad-hoc-jobs-for-later-on-an-instance-with-atd.md
- Stocks:
  - Netflix Quarterly Growth: stocks/nflx-quarterly-subscriber-growth.md
- Talks:
  - Favorite: talks/favorite.md
  - Netflix Atlas Telemetry - A Platform Begets an Ecosystem: talks/netflix-atlas-telemetry-a-platform-begets-an-ecosystem.md

theme: material

extra:
  font:
    code: 'Menlo'

extra_css:
- css/custom.css

extra_javascript:
- https://buttons.github.io/buttons.js

markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.tilde
- toc:
    permalink: True
