site_name: Copperlight Writes
site_url: 'https://copperlight.github.io/'
repo_url: 'https://github.com/copperlight/copperlight.github.io'
edit_uri: ''
site_description: A site for knowledge sharing and neat things.
site_author: Matthew Johnson
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>

strict: True

theme: material

extra:
  analytics:
    provider: google
    property: G-DC72N3VD1X

extra_css:
  - css/custom.css

extra_javascript:
  - https://buttons.github.io/buttons.js

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: True

plugins:
  - blog
  - search
